### ISSUE TITLE
Permission fragment error with kotlin androidx  alpha03

### ISSUE THREAD

**Issue by KONFeature** [florent37/RuntimePermission#25]
When i updated from android.material alpha02 to alpha03 i have this strange comportement when i start to ask for permission : 

 - First permission popup that i decline
 - My dialog that tell the user to accept permission, and the positiveButon click launch permissionResult.askAgain()
 - Nothing (no popup or anything comming at the screen), and when i click on the multi task button the app crashed 

Stacktrace : 
`02-20 17:32:40.541 18236-18236/com.sncf.android.internal.mobileocarvente.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sncf.android.internal.mobileocarvente.dev, PID: 18236
    java.lang.IllegalStateException: Failure saving state: active PermissionFragment{46f00ad (e39d268c-17ad-47b7-8172-7cf87735488d) PERMISSION_FRAGMENT_WEEEEE} was removed from the FragmentManager
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2315)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at android.app.Activity.performSaveInstanceState(Activity.java:1487)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1318)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5483)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4773)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4847)
        at android.app.ActivityThread.access$1400(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1850)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

Running on galaxy A5 with SDK 23.

**Comment by sunil19822701** [comment]
Similar problem on calling settings
code
askPermission{
            Log.d(MainActivity::class.java.canonicalName,"Accepted Request")
        }.onDeclined { e ->
            e.foreverDenied.forEach {
                perms->
                Log.d(MainActivity::class.java.canonicalName,perms)
            }
            //at least one permission have been declined by the user
            if(e.hasForeverDenied())
            {
                e.goToSettings()
            }
        }
Stack Trace
Process: io.teseract.mockapp, PID: 18165
    java.lang.IllegalStateException: Failure saving state: active PermissionFragment{a6d4191 (0e92dc56-b55e-4df9-94b2-109a5618951e) PERMISSION_FRAGMENT_WEEEEE} was removed from the FragmentManager
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2315)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at android.app.Activity.performSaveInstanceState(Activity.java:1550)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1443)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:4848)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4195)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4159)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4234)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by DamonBaker** [comment]
The issue appears to be on line 24 of PermissionFragment: `setRetainInstance(true);`
[This stackoverflow answer](https://stackoverflow.com/a/54104362/10715642) gives some background to the reason why the crash occurs.

A temporary workaround is to find the fragment by it's tag after you add it and manually call `setRetainInstance(false);`

Example:
```
private fun requestPermissions() {
    askPermission() {
        // Accepted
        Timber.d(it.toString())
    }.onDeclined { permissionResult ->
        if (permissionResult.hasDenied()) {
            AlertDialog.Builder(this)
                .setTitle("Please accept our permissions")
                .setMessage("This app may not function as expected without these permissions enabled.")
                .setPositiveButton("Agree") { _, _ ->
                    requestPermissions()
                }
                .setNegativeButton("Cancel") { dialog, _ ->
                    dialog.dismiss()
                }
                .show()
        }
    }

    // Yes that's actually the tag
    supportFragmentManager.findFragmentByTag("PERMISSION_FRAGMENT_WEEEEE")?.let { fragment ->
        fragment.retainInstance = false
    }
}
```

I'm not sure what the original intent was of setting the fragment to retain instance, but there doesn't appear to be any side-effects of disabling it. Maybe it was to prevent the fragment from being unnecessarily re-initialised after configuration changes, since it isn't a "visual" fragment.
